version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
      POSTGRES_DB: chat_db
    ports:
      - "5432:5432"
    volumes:
      - chat_db_data:/var/lib/postgresql/data
    networks:
      - chat_network

networks:
  chat_network:

volumes:
  chat_db_data:
